services:
  - type: web
    name: financial-advisor-chat
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn financial_advisor_chat:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_API_KEY
        sync: false 